ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('', include('ProyectoWebApp.urls')),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.blog, name ='Blog'),
    path('categoria/<int:categoria_id>/', views.categoria, name='categoria')

]

carro/urls.py
from django.urls import path
from . import views

app_name = "carro"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name='eliminar'),
    path('restar/<int:producto_id>/', views.restar_producto, name='restar'),
    path('limpiar/', views.limpiar_carro, name='limpiar'),
]

tienda/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.tienda, name ='Tienda'),
]

carro/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models

# Create your models here.


class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta: #Para especificar el nombre que va a tener en singular y en plural la categoria
        verbose_name="categoriaProd"
        verbose_name_plural="categoriasProd"
    
    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    categorias = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE) #Campo clave foránea
    imagen = models.ImageField(upload_to="tienda", null=True, blank=True) #Hace falta tener instalado pillow
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "productos"

    def __str__(self):
        return self.nombre

carro/views.py
from django.shortcuts import render

from .carro import Carro

from tienda.models import Producto

from django.shortcuts import redirect # Para redireccionar cuando realicemos alguna operacion para que refleje esos cambios.
# Create your views here.

def agregar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.agregar(producto=producto)

    return redirect("Tienda")


def eliminar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.eliminar(producto=producto)

    return redirect("Tienda")


def restar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.restar_producto(producto=producto)

    return redirect("Tienda")


def limpiar_carro(request, producto_id):

    carro=Carro(request)

    carro.limpiar_carro()

    return redirect("Tienda")

tienda/views.py
from django.shortcuts import render
from .models import Producto

# Create your views here.


def tienda(request):

    productos = Producto.objects.all()
    return render(request, 'tienda/tienda.html', {'productos':productos})

tienda/templates/carro/widget.html
<table class="table table-bordered" style="color: rgb(0, 0, 0); background-color: rgba(206, 206, 206, 0.8); border-color: black;">

    <thead style="border-color: black;">
        <tr style="border-color: black;">
            <th colspan="3" class="text-center" style="border-color: black;">
                Carro compras
            </th>
        </tr>
        <tr style="border-color: black;">
            <th style="border-color: black;">Producto</th>
            <th style="border-color: black;">Cantidad</th>
            <th style="border-color: black;">Suma</th>
        </tr>
    </thead>

    <tbody style="border-color: black;">
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center" style="border-color: black;">
                    <td style="border-color: black;">{{value.nombre}}</td>
                    <td style="border-color: black;">{{value.cantidad}}</td>
                    <td style="border-color: black;">
                        <a href="{%  url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-warning">+</a>
                        <a href="{%  url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-warning">-</a><br>
                        {{value.precio}}€
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr style="border-color: black;">
                <td colspan="3" style="border-color: black;">
                    <div class="alert alert-danger text-center">
                        Sin productos
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>

    <tfoot style="border-color: black;">
        <tr style="border-color: black;">
            <td colspan="3" style="border-color: black;">
                Total: {{importe_total_carro}} €
            </td>
        </tr>
        {% if request.session.carro.items %}
        <tr style="border-color: black;">
            <td colspan="3" style="text-align: center; border-color: black;">
                <a href="{% url 'procesar_pedido' %}" class="btn btn-warning">Realizar Pedido</a>
            </td>
        </tr>
        {% endif %}
    </tfoot>
</table>